# Site settings
author: Marci Clark
title: Marci Learns To Program
header-img: img/home-bg.png
email: marcig612@gmail.com
copyright_name: Marci Clark
description: > # this means to ignore newlines until "baseurl:"
  This is going to be a bumpy ride. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MarciClark

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
